kind: pipeline
name: x86_64_linux_gcc
type: docker

platform:
  arch: amd64
  os: linux
  abi: CXXABI_1.3.13

steps:
- name: version_info
  pull: never
  image: aeon_ci/x86_64_linux_gcc
  commands:
  - cat /ubuntu_version
  - cat /ubuntu_version_name
  - cmake --version
  - git --version
  - $CC --version
  - $CXX --version

- name: git
  pull: never
  image: aeon_ci/x86_64_linux_gcc
  commands:
  - git submodule update --init

- name: cmake
  pull: never
  image: aeon_ci/x86_64_linux_gcc
  commands:
  - cmake -S . -B /tmp/build-volume -G "Unix Makefiles"
  volumes:
  - name: build-volume
    path: /tmp/build-volume

- name: build
  pull: never
  image: aeon_ci/x86_64_linux_gcc
  commands:
  - cmake --build /tmp/build-volume -j2
  volumes:
  - name: build-volume
    path: /tmp/build-volume

- name: test
  pull: never
  image: aeon_ci/x86_64_linux_gcc
  commands:
  - cd /tmp/build-volume
  - ctest --verbose
  volumes:
  - name: build-volume
    path: /tmp/build-volume

volumes:
  - name: build-volume
    temp: {}

node:
    platform: linux

---

kind: pipeline
name: x86_64_linux_clang
type: docker

platform:
  arch: amd64
  os: linux
  abi: CXXABI_1.3.13

steps:
- name: version_info
  pull: never
  image: aeon_ci/x86_64_linux_clang
  commands:
  - cat /ubuntu_version
  - cat /ubuntu_version_name
  - cmake --version
  - git --version
  - $CC --version
  - $CXX --version

- name: git
  pull: never
  image: aeon_ci/x86_64_linux_clang
  commands:
  - git submodule update --init

- name: cmake
  pull: never
  image: aeon_ci/x86_64_linux_clang
  commands:
  - cmake -S . -B /tmp/build-volume -G "Unix Makefiles"
  volumes:
  - name: build-volume
    path: /tmp/build-volume

- name: build
  pull: never
  image: aeon_ci/x86_64_linux_clang
  commands:
  - cmake --build /tmp/build-volume -j2
  volumes:
  - name: build-volume
    path: /tmp/build-volume

- name: test
  pull: never
  image: aeon_ci/x86_64_linux_clang
  commands:
  - cd /tmp/build-volume
  - ctest --verbose
  volumes:
  - name: build-volume
    path: /tmp/build-volume

volumes:
  - name: build-volume
    temp: {}

node:
    platform: linux

---

kind: pipeline
name: libaeon-build-vs2019
type: exec

platform:
    arch: amd64
    os: windows
    abi: vc142

steps:
- name: version_info
  commands:
  - Get-ComputerInfo | select windowsversion
  - Get-ComputerInfo | select OsVersion
  - cmake --version
  - git --version

- name: git
  commands:
  - git submodule update --init

- name: cmake
  commands:
  - New-Item -Name "build" -ItemType "directory"
  - Set-Location "build"
  - cmake --% .. -G "Visual Studio 16 2019" -T host=x64 -A x64 -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_INSTALL_PREFIX=install -DAEON_EXTERNAL_DEPENDENCIES_DIR=C:/ExternalDependencies/

- name: build
  commands:
  - Set-Location "build"
  - cmake --% --build . --config Debug -- /m

- name: test
  commands:
  - Set-Location "build"
  - ctest --% -C Debug --verbose

node:
    platform: windows
