osx:
  tags:
    - osx
  script:
    - export WORKSPACE=$PWD
    - cd $AEON_LIBRARIES_PATH
    - git checkout origin/master
    - git fetch --prune
    - cd $WORKSPACE
    - export BUILD_DIR=ci_build
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -DCMAKE_INSTALL_PREFIX=install ../
    - cmake --build . --target install --config Debug
    - ctest -C Debug --verbose

windows:
  tags:
    - windows
  script:
    - pushd "%AEON_LIBRARIES_PATH%"
    - git checkout origin/master
    - git fetch --prune
    - popd
    - mkdir ci_build
    - cd ci_build
    - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=install ../
    - cmake --build . --target install --config Debug

cppcheck:
  tags:
    - osx
  script:
    - cppcheck --enable=style,information,missingInclude --std=posix -q -I include/ src
