language: cpp

matrix:
  include:
    - os: linux
      compiler: clang++
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - mono-devel
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_VERSION_STRING=3.10.1
        - CLANG_VERSION_STRING=5.0.1
        - BUILD_ENVIRONMENT_NAME=linux
    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_VERSION_STRING=3.10.1
        - CLANG_VERSION_STRING=5.0.1
        - BUILD_ENVIRONMENT_NAME=macos

script:
  - source ci/common_clang.sh
  - source ci/${BUILD_ENVIRONMENT_NAME}_clang.sh
