language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - mono-devel
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_VERSION_STRING=3.10.1
        - CLANG_VERSION_STRING=5.0.1
        - BUILD_ENVIRONMENT_NAME=linux
    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_VERSION_STRING=3.10.1
        - CLANG_VERSION_STRING=5.0.1
        - BUILD_ENVIRONMENT_NAME=macos

script:
  - wget https://dl.bintray.com/aeon-engine/aeon_engine_dependencies/cmake/${CMAKE_VERSION_STRING}/cmake_${BUILD_ENVIRONMENT_NAME}.tar.gz
  - wget https://dl.bintray.com/aeon-engine/aeon_engine_dependencies/clang/${CLANG_VERSION_STRING}/clang_${BUILD_ENVIRONMENT_NAME}.tar.xz
  - tar xf cmake_${BUILD_ENVIRONMENT_NAME}.tar.gz
  - export PATH=$(pwd)/$(find . -maxdepth 1 -type d -name 'cmake-*')/bin:$PATH
  - tar xf clang_${BUILD_ENVIRONMENT_NAME}.tar.xz
  - export CLANG_BASE_PATH=$(pwd)/$(find . -maxdepth 1 -type d -name 'clang+llvm*')
  - export PATH=${CLANG_BASE_PATH}/bin:$PATH
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$COMPILER_CC -DCMAKE_CXX_COMPILER=$COMPILER_CXX -DAEON_ENABLE_CURL=1 -DAEON_ENABLE_SOCKETS=1 -DAEON_ENABLE_MIDI=1 -DAEON_ENABLE_HDF5=1 -DCMAKE_SYSROOT=${CLANG_BASE_PATH}
  - make
  - ctest -C Debug --verbose
