name: Linux x86_64 GCC 12

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aeonengine/linux_x86_64:gcc12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Conan remote
        run: conan config install remotes.txt

      - name: Conan install
        run: conan install . -if build -pr ./conan/profiles/linux_gcc12_x64 -s build_type=Debug

      - name: Cmake
        run: cmake . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/build/install -DCMAKE_BUILD_TYPE=Debug -DAEON_ENABLE_CONAN_INTEGRATION=0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
