name: linux_gcc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: aeonengine/linux_build_environment

    steps:
    - uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init

    - name: Bootstrap
      run: mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=$(pwd)/install

    - name: Build
      run: cd build && make -j2

    - name: Test
      run: cd build && ctest
