name: Windows x86_64 VS2022

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Conan install
        run: python -m pip install conan

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Conan remote
        run: conan config install remotes.txt

      - name: Conan install
        run: |
            conan install . -if build -pr ./conan/profiles/visual_studio_2022_x64 -s build_type=Debug
            conan install . -if build -pr ./conan/profiles/visual_studio_2022_x64 -s build_type=Release

      - name: Cmake
        run: cmake . -B build -G "Visual Studio 17 2022" -T host=x64 -A x64 -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_INSTALL_PREFIX=%CD%/build/install -DAEON_ENABLE_CONAN_INTEGRATION=0

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ctest --test-dir build -C Debug
